/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as ResultsMatchIdRouteImport } from './routes/results.$matchId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultsRoute,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const ResultsMatchIdRoute = ResultsMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => ResultsRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/players': typeof PlayersRouteWithChildren
  '/results': typeof ResultsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/videos': typeof VideosRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/results/$matchId': typeof ResultsMatchIdRoute
  '/players/': typeof PlayersIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/videos': typeof VideosRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/results/$matchId': typeof ResultsMatchIdRoute
  '/players': typeof PlayersIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/players': typeof PlayersRouteWithChildren
  '/results': typeof ResultsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/videos': typeof VideosRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/results/$matchId': typeof ResultsMatchIdRoute
  '/players/': typeof PlayersIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/players'
    | '/results'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/videos'
    | '/players/$playerId'
    | '/results/$matchId'
    | '/players/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/videos'
    | '/players/$playerId'
    | '/results/$matchId'
    | '/players'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/players'
    | '/results'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/videos'
    | '/players/$playerId'
    | '/results/$matchId'
    | '/players/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  ResultsRoute: typeof ResultsRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  StandingsRoute: typeof StandingsRoute
  StatsRoute: typeof StatsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/results/$matchId': {
      id: '/results/$matchId'
      path: '/$matchId'
      fullPath: '/results/$matchId'
      preLoaderRoute: typeof ResultsMatchIdRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface ResultsRouteChildren {
  ResultsMatchIdRoute: typeof ResultsMatchIdRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsMatchIdRoute: ResultsMatchIdRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  PlayersRoute: PlayersRouteWithChildren,
  ResultsRoute: ResultsRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  StandingsRoute: StandingsRoute,
  StatsRoute: StatsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
